# https://quarto.org/docs/reference/formats/ipynb.html
format:
  ipynb:
    execute:
      eval: false
      echo: true
      output: true
      warning: true
      error: true
      include: true
      cache: false
      freeze: false